Updates openssl, opens, and sysstat.
More robustness in Phase 1 build.  Supports "continue" mode (with
partial build).  Allows "cached" download files.  Disables any
framebuffer in the console (80x25 only).

diff --git a/lfs b/lfs
--- a/lfs
+++ b/lfs
@@ -10,7 +10,7 @@ echo "########################################################################"
 echo
 echo "  Looking for config file..."
 
-XLAPP_VERSION="7.0.4"
+XLAPP_VERSION="7.0.6"
 XLAPP_CONFIG_FILE="machine.config"
 
 ./lfs-conf "${@}"
@@ -46,6 +46,8 @@ if [ -z $XLAPP_LFS ] ; then
 	false
 fi
 
+XLAPP_BUILD_OUTPUT=~/lfs-${XLAPP_TOTIME}.out
+
 echo "  Setting \$LFS to [ ${XLAPP_LFS} ]..."
 if [ -n "$XLAPP_USE_RAMFS" ] ; then
 	export LFS=/mnt/xlapp-build-ram
@@ -60,161 +62,208 @@ else
 	_EXTRA_BUILD_MESG=" Verified Build (with ALL tests)"
 fi
 
+# ========================================================================
+# ========================================================================
+# ========================================================================
+# ========================================================================
+# ========================================================================
+#
+# (This is the start of the big "is-continuing?" 'if' block.)
+#
+# BEGIN_IF
+#
+# ========================================================================
+# ========================================================================
+# ========================================================================
+# ========================================================================
+# ========================================================================
 if [ -z $XLAPP_CONTINUE ] ; then # If XLAPP_CONTINUE isn't set, do prep/init.
-echo "  Creating .bashrc for LFS-user, and lfs-05-buid-as-lfs..."
-LFS_DOT_BASHRC="dot.bashrc-lfs"
-cat ${LFS_DOT_BASHRC}.in | sed "s,^LFS=.*,LFS=$LFS," > $LFS_DOT_BASHRC
-LFS_05_BUILD="lfs-05-build-as-lfs"
-cat ${LFS_05_BUILD}.in | sed "s,^LFS=.*,LFS=$LFS," > $LFS_05_BUILD
-ROOT_DOT_ALIAS_ROOT="dot.alias-root"
-cat ${ROOT_DOT_ALIAS_ROOT}.in | sed "s,^LFS=.*,LFS=$LFS," > $ROOT_DOT_ALIAS_ROOT
 
-/bin/cp -fv $ROOT_DOT_ALIAS_ROOT ~root/.alias-root
+    echo "  Creating .bashrc for LFS-user, and lfs-05-buid-as-lfs..."
+    LFS_DOT_BASHRC="dot.bashrc-lfs"
+    cat ${LFS_DOT_BASHRC}.in | sed "s,^LFS=.*,LFS=$LFS," > $LFS_DOT_BASHRC
+    LFS_05_BUILD="lfs-05-build-as-lfs"
+    cat ${LFS_05_BUILD}.in | sed "s,^LFS=.*,LFS=$LFS," > $LFS_05_BUILD
+    ROOT_DOT_ALIAS_ROOT="dot.alias-root"
+    cat ${ROOT_DOT_ALIAS_ROOT}.in | sed "s,^LFS=.*,LFS=$LFS," > $ROOT_DOT_ALIAS_ROOT
 
-echo -n "  Skipping tests? "
-if [ -n $SKIP_TESTS ] ; then echo "Yes." ; else echo "No." ; fi
-echo "  \$MAKEFLAGS? ${MAKEFLAGS}"
+    /bin/cp -fv $ROOT_DOT_ALIAS_ROOT ~root/.alias-root
 
-echo "  Checking \$LFS var..."
-# We need to test if $LFS is /; if so, abort.  Otherwise, this will be devastating.
-if [ -z $LFS ] ; then echo "LFS is unset, which is improper; aborting!!" ; exit ; fi
-if [ "$LFS" == "" ] ; then echo "LFS is set to an empty string, an invalid value; aborting!!" ; exit ; fi
-if [ "$LFS" == "/" ] ; then echo "LFS is set to the root directory, an invalid value; aborting!!" ; exit ; fi
+    echo -n "  Skipping tests? "
+    if [ -n $SKIP_TESTS ] ; then echo "Yes." ; else echo "No." ; fi
+    echo "  \$MAKEFLAGS? ${MAKEFLAGS}"
 
-if [ -d $LFS ] ; then
-	pushd $LFS > /dev/null
-	if [ $(pwd) == "/" ] ; then echo "LFS is equivalent to the root directory, which is improper; aborting!!" ; exit ; fi
-	popd > /dev/null
-fi
+    echo "  Checking \$LFS var..."
+    # We need to test if $LFS is /; if so, abort.  Otherwise, this will be devastating.
+    if [ -z $LFS ] ; then echo "LFS is unset, which is improper; aborting!!" ; exit ; fi
+    if [ "$LFS" == "" ] ; then echo "LFS is set to an empty string, an invalid value; aborting!!" ; exit ; fi
+    if [ "$LFS" == "/" ] ; then echo "LFS is set to the root directory, an invalid value; aborting!!" ; exit ; fi
 
-echo "  Unmounting LFS partitions..."
-set +e
-umount $LFS/sys 2> /dev/null
-umount $LFS/proc 2> /dev/null
-umount $LFS/dev/pts 2> /dev/null
-umount $LFS/dev/shm 2> /dev/null
-umount $LFS/dev 2> /dev/null
-# Again, unmounting used to make sense, but doesn't if we want to try
-# to install-to-/boot.  In fact, we want to make sure the mount-point
-# exists, and is mounted.
-#umount $LFS 2> /dev/null
-#umount ${XLAPP_LFS_PART} 2> /dev/null
-echo "  Make sure LFS mount point [ $LFS ] exists and is mounted..."
-mkdir -pv $LFS
-if [ -z "$XLAPP_USE_RAMFS" ] ; then
-	mount ${XLAPP_LFS_PART} $LFS
-else
-	umount -v $LFS
-	mount -v -t tmpfs -o size=16384m tmpfs $LFS
-fi
-set -e
+    if [ -d $LFS ] ; then
+        pushd $LFS > /dev/null
+        if [ $(pwd) == "/" ] ; then echo "LFS is equivalent to the root directory, which is improper; aborting!!" ; exit ; fi
+        popd > /dev/null
+    fi
 
-#exit #TMPFS - testing.
+    echo "  Unmounting LFS partitions..."
+    set +e
+    umount $LFS/sys 2> /dev/null
+    umount $LFS/proc 2> /dev/null
+    umount $LFS/dev/pts 2> /dev/null
+    umount $LFS/dev/shm 2> /dev/null
+    umount $LFS/dev 2> /dev/null
+    # Again, unmounting used to make sense, but doesn't if we want to try
+    # to install-to-/boot.  In fact, we want to make sure the mount-point
+    # exists, and is mounted.
+    #umount $LFS 2> /dev/null
+    #umount ${XLAPP_LFS_PART} 2> /dev/null
+    echo "  Make sure LFS mount point [ $LFS ] exists and is mounted..."
+    mkdir -pv $LFS
+    if [ -z "$XLAPP_USE_RAMFS" ] ; then
+        mount ${XLAPP_LFS_PART} $LFS
+    else
+        umount -v $LFS
+        mount -v -t tmpfs -o size=16384m tmpfs $LFS
+    fi
+    set -e
 
-########################################################################
+    #exit #TMPFS - testing.
+
+    ########################################################################
+    #
+    # This used to make sense, but doesn't if want to try install-to-/boot
+    #
+    #echo "  Create LFS partition filesystem..."
+    #mkfs -t ${XLAPP_BOOT_FSTYPE} ${XLAPP_LFS_PART}
+
+    #echo "  Mounting LFS partition [ ${XLAPP_LFS_PART} ] at [ ${LFS} ]..."
+    #mount ${XLAPP_LFS_PART} $LFS
+    ########################################################################
+
+    #
+    # Assume that $LFS might be a boot partition.  So, don't remove /boot files.
+    #
+    find $LFS/ -mindepth 1 -maxdepth 1 -type d \( -not -name "grub*" -a -not -name "lost+found" \) -exec rm -rf {} \;
+    /bin/rm -f $LFS/tools
+
+    echo "  Creating LFS work directory [ ${__SOURCE_DIR} ]..."
+    mkdir -pv $__SOURCE_DIR
+    chmod -v a+wt $__SOURCE_DIR
+
+    echo "  Copying XLAPP scripts..."
+    cp -a * $__SOURCE_DIR
+    #if [ -z $SKIP_TESTS ] ; then
+        #for CHAP_SIX_PKG in $(grep -l "^#test " 6*) ; do
+            #echo "  Uncommenting tests for package [ $CHAP_SIX_PKG ]..."
+            #cat $CHAP_SIX_PKG | sed 's/^\(\s*\)#test /\1/' > $__SOURCE_DIR/$CHAP_SIX_PKG
+        #done
+    #fi
+
+    XLAPP_FILES_MD5SUMS="$__SOURCE_DIR/src/_md5sums-${XLAPP_VERSION}"
+    XLAPP_FILES_WGET_LIST="$__SOURCE_DIR/src/_wget-${XLAPP_VERSION}"
+
+    echo "  Checking MD5 sums on packages..."
+    if [ -z $XLAPP_FILES_SOURCE ] ; then
+        XLAPP_FILES_SOURCE="$__SOURCE_DIR/src"
+    else
+        echo "    (Using cached source location...)"
+        __DOWNLOAD_TO_ALT=true
+    fi
+
+    pushd $XLAPP_FILES_SOURCE
+
+    for download in $(cat $XLAPP_FILES_WGET_LIST) ; do
+        download_file=$(basename $download)
+        if [ ! -f $download_file ] ; then wget $download ; fi
+        if [ -n "$__DOWNLOAD_TO_ALT" ] ; then cp $download_file $__SOURCE_DIR/src ; fi
+    done
+
+    if [ -n "$__DOWNLOAD_TO_ALT" ] ; then
+        popd
+        pushd $__SOURCE_DIR/src
+    fi
+
+    #wget -nc -i _wget-7.0.1
+    md5sum -c $XLAPP_FILES_MD5SUMS
+    if [ 0 -ne $? ] ; then echo "MD5 sums failed to match; aborting hard." ; exit 1 ; fi
+    popd
+
+    #
+    # Starting book
+    #
+    echo "  Starting LFS build..."
+    mkdir -pv $LFS/tools
+    if [ -L /tools ] ; then
+        rm -f /tools
+    fi
+    ln -sv $LFS/tools /
+
+    echo "    Adding LFS user (lfs) to LFS-host system..."
+    set +e
+    id lfs
+    if [ 0 -eq $? ] ; then
+        echo "LFS user already existed; removing..."
+        userdel lfs
+        groupdel lfs
+    fi
+    set -e
+
+    if [ -d /etc/skel ] ; then
+        /bin/mv -f /etc/skel /etc/skel-ORIG
+    fi
+    /bin/mkdir -p /etc/skel
+    /bin/chmod 0755 /etc/skel
+    groupadd lfs
+    useradd -s /bin/bash -g lfs -m lfs
+    /bin/cp -fv dot.bashrc-lfs /home/lfs/.bashrc
+    /bin/cp -fv dot.bash_profile-lfs /home/lfs/.bash_profile
+    /bin/cp -fv lfs-05-build-as-lfs /home/lfs
+    /bin/chown -v lfs:lfs /home/lfs/.bash* /home/lfs/lfs-*
+    /bin/chmod -v 0755 /home/lfs/lfs-*
+
+    chown -v lfs:lfs $LFS/tools
+    chown -v lfs:lfs $__SOURCE_DIR
+    chown -Rv lfs:lfs $__SOURCE_DIR/src
+
+    # Add password for lfs in /etc/shadow
+    sed -i "s%^lfs:[^:]*:\(.*\)%lfs:$XLAPP_ROOT_PASSWD_HASH:\1%" /etc/shadow
+
+    rm -f $XLAPP_BUILD_OUTPUT
+    #rm -f $__SOURCE_DIR/lfs.out
+    find src -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} \;
+    ln -sfv $XLAPP_BUILD_OUTPUT ./lfs.out
+    #ln -sfv $__SOURCE_DIR/lfs.out ./lfs.out
+    rm -rf $__SOURCE_DIR/tests
+    mkdir -pv $__SOURCE_DIR/tests
+    ln -sfv $__SOURCE_DIR/tests ./tests
+
+    echo "########################################################################"
+    echo "#"
+    echo "# Building XLAPP (Phase 1) - ${_EXTRA_BUILD_MESG}..."
+    echo "#"
+    echo "#   * Use tail -f lfs.out to see build outout."
+    echo "#"
+    echo "#   * This process will not produce more output until completion."
+    echo "*"
+    echo "# Compilation starting at: ${XLAPP_TOTIME}"
+    echo "#"
+    echo "########################################################################"
+
+# ========================================================================
+# ========================================================================
+# ========================================================================
+# ========================================================================
+# ========================================================================
 #
-# This used to make sense, but doesn't if want to try install-to-/boot
+# (This is the terminal of the 'if' block started way up high.)
 #
-#echo "  Create LFS partition filesystem..."
-#mkfs -t ${XLAPP_BOOT_FSTYPE} ${XLAPP_LFS_PART}
-
-#echo "  Mounting LFS partition [ ${XLAPP_LFS_PART} ] at [ ${LFS} ]..."
-#mount ${XLAPP_LFS_PART} $LFS
-########################################################################
-
+# END_IF
 #
-# Assume that $LFS might be a boot partition.  So, don't remove /boot files.
-#
-find $LFS/ -mindepth 1 -maxdepth 1 -type d \( -not -name "grub*" -a -not -name "lost+found" \) -exec rm -rf {} \;
-/bin/rm -f $LFS/tools
-
-echo "  Creating LFS work directory [ ${__SOURCE_DIR} ]..."
-mkdir -pv $__SOURCE_DIR
-chmod -v a+wt $__SOURCE_DIR
-
-echo "  Copying XLAPP scripts..."
-cp -a * $__SOURCE_DIR
-#if [ -z $SKIP_TESTS ] ; then
-	#for CHAP_SIX_PKG in $(grep -l "^#test " 6*) ; do
-		#echo "  Uncommenting tests for package [ $CHAP_SIX_PKG ]..."
-		#cat $CHAP_SIX_PKG | sed 's/^\(\s*\)#test /\1/' > $__SOURCE_DIR/$CHAP_SIX_PKG
-	#done
-#fi
-
-echo "  Checking MD5 sums on packages..."
-pushd $__SOURCE_DIR/src
-
-for download in $(cat _wget-${XLAPP_VERSION}) ; do
-	download_file=$(basename $download)
-	if [ ! -f $download_file ] ; then
-		wget $download
-	fi
-done
-
-#wget -nc -i _wget-7.0.1
-md5sum -c _md5sums
-if [ 0 -ne $? ] ; then echo "MD5 sums failed to match; aborting hard." ; exit 1 ; fi
-popd
-
-#
-# Starting book
-#
-echo "  Starting LFS build..."
-mkdir -pv $LFS/tools
-if [ -L /tools ] ; then
-	rm -f /tools
-fi
-ln -sv $LFS/tools /
-
-echo "    Adding LFS user (lfs) to LFS-host system..."
-set +e
-id lfs
-if [ 0 -eq $? ] ; then
-	echo "LFS user already existed; removing..."
-	userdel lfs
-	groupdel lfs
-fi
-set -e
-
-if [ -d /etc/skel ] ; then
-	/bin/mv -f /etc/skel /etc/skel-ORIG
-fi
-/bin/mkdir -p /etc/skel
-/bin/chmod 0755 /etc/skel
-groupadd lfs
-useradd -s /bin/bash -g lfs -m lfs
-/bin/cp -fv dot.bashrc-lfs /home/lfs/.bashrc
-/bin/cp -fv dot.bash_profile-lfs /home/lfs/.bash_profile
-/bin/cp -fv lfs-05-build-as-lfs /home/lfs
-/bin/chown -v lfs:lfs /home/lfs/.bash* /home/lfs/lfs-*
-/bin/chmod -v 0755 /home/lfs/lfs-*
-
-chown -v lfs:lfs $LFS/tools
-chown -v lfs:lfs $__SOURCE_DIR
-chown -Rv lfs:lfs $__SOURCE_DIR/src
-
-# Add password for lfs in /etc/shadow
-sed -i "s%^lfs:[^:]*:\(.*\)%lfs:$XLAPP_ROOT_PASSWD_HASH:\1%" /etc/shadow
-
-echo "########################################################################"
-echo "#"
-echo "# Building XLAPP (Phase 1) - ${_EXTRA_BUILD_MESG}..."
-echo "#"
-echo "#   * Use tail -f lfs.out to see build outout."
-echo "#"
-echo "#   * This process will not produce more output until completion."
-echo "#"
-echo "########################################################################"
-
-#
-# Start compiling stuff!
-#
-rm -f $__SOURCE_DIR/lfs.out
-find src -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} \;
-ln -sfv $__SOURCE_DIR/lfs.out ./lfs.out
-rm -rf $__SOURCE_DIR/tests
-mkdir -pv $__SOURCE_DIR/tests
-ln -sfv $__SOURCE_DIR/tests ./tests
+# ========================================================================
+# ========================================================================
+# ========================================================================
+# ========================================================================
+# ========================================================================
 else # XLAPP_CONTINUE is not set.
 	echo "########################################################################"
 	echo "#"
@@ -229,8 +278,8 @@ fi
 
 cd $__SOURCE_DIR
 set +e
-touch $__SOURCE_DIR/lfs.out
-time ./lfs-actual >> $__SOURCE_DIR/lfs.out 2>&1
+touch $XLAPP_BUILD_OUTPUT
+time ./lfs-actual >> $XLAPP_BUILD_OUTPUT 2>&1
 
 if [ 0 -ne $? ] ; then
 	echo "########################################################################"
@@ -247,11 +296,6 @@ set -e
 #
 # Copy the kernel to the existing /boot...
 #
-totime()
-{
-	date '+%Y%m%d_%H%M%S'
-}
-
 echo "    Installing new dom0-capaable kernel: lfs-7.0-linux-3.1..."
 for file in $(echo $LFS/boot/*) ; do
 	/bin/cp -vf $file /boot
