Allows MTU in ifconfig.X files.
/sbin/ifup, /sbin/ifdown, /lib/lsb/bridge, and /lib/lsb/ipv4-config
have been modified to allow the /sbin scripts to handle the PHY
link--including setting the per-link MTU--and let the downstream
/lib/lsb scripts handle service-specific configuration.

Downstream scripts are passed the ifcongig.X file (instead of just the
short name).  All service-specific variables need to be set explicitly
(e.g., BRIDGE_IF).

This entailed making ipv4-static a bit smarter (it will use an explicit
IPV4_IF if set; otherwise, will use the first PHYS).

The script bridge needed to be modified to use BRIDGE_IF, and to stop
trying to handle the PHY links.

diff --git a/xlapp-bootscripts/bridge b/xlapp-bootscripts/bridge
--- a/xlapp-bootscripts/bridge
+++ b/xlapp-bootscripts/bridge
@@ -12,24 +12,30 @@
 ########################################################################
 
 . /lib/lsb/init-functions
+
+if [ -z ${1} ] ; then
+  log_failure_msg "No ifconfig file specified"
+  exit 1
+fi
+IFCONFIG=$1
 . ${IFCONFIG}
 
-if [ -n "${INTERFACE}" ]; then
-  log_failure_msg "INTERFACES variable missing from ${IFCONFIG}"
+# Call the bridge ${BRIDGE_IF} for clarity.
+if [ -z ${BRIDGE_IF} ]; then
+  log_failure_msg "BRIDGE_IF variable missing from ${IFCONFIG}"
   exit 1
 fi
 
 case "${2}" in
   up)
      log_info_msg2 "\n"
-     log_info_msg "Creating the ${1} interface..."
-     brctl addbr ${1}
-     ip link set ${1} up
+     log_info_msg "Creating the ${BRIDGE_IF} interface..."
+     brctl addbr ${BRIDGE_IF}
+     ip link set ${BRIDGE_IF} up
      evaluate_retval
-     for I in ${INTERFACES}; do
-        log_info_msg "Adding ${I} to ${1}..."
-        ip link set ${I} up &&
-        brctl addif ${1} ${I}
+     for PHY in ${PHYS}; do
+        log_info_msg "Adding ${PHY} to ${BRIDGE_IF}..."
+        brctl addif ${BRIDGE_IF} ${PHY}
         evaluate_retval
      done
 
@@ -44,21 +50,20 @@ case "${2}" in
   ;;
 
   down)
-     for I in ${INTERFACES}; do
-        log_info_msg "Removing ${I} from ${1}..."
-        ip link set ${I} down &&
-        brctl delif ${1} ${I}
+     for PHY in ${PHYS}; do
+        log_info_msg "Removing ${PHY} from ${BRIDGE_IF}..."
+        brctl delif ${BRIDGE_IF} ${PHY}
         evaluate_retval
      done
 
-     log_info_msg "Bringing down the ${1} interface..."
-     ip link set ${1} down
-     brctl delbr ${1}
+     log_info_msg "Bringing down the ${BRIDGE_IF} interface..."
+     ip link set ${BRIDGE_IF} down
+     brctl delbr ${BRIDGE_IF}
      evaluate_retval
   ;;
 
   *)
-     echo "Usage: ${0} [interface] {up|down}"
+     echo "Usage: ${0} <ifconfig-file> {up|down}"
      exit 1
   ;;
 esac
diff --git a/xlapp-bootscripts/ifup b/xlapp-bootscripts/ifup
--- a/xlapp-bootscripts/ifup
+++ b/xlapp-bootscripts/ifup
@@ -10,7 +10,7 @@
 #
 # Version     : LFS 7.0
 #
-# Notes       : The IFCONFIG variable is passed to the SERVICE script
+# Notes       : The ${file} variable is passed to the SERVICE script
 #               in the /lib/services directory, to indicate what file the
 #               service should source to get interface specifications.
 #
@@ -55,19 +55,12 @@ file=/etc/sysconfig/ifconfig.${1}
 
 . /lib/lsb/init-functions
 
-log_info_msg "Bringing up the ${1} interface... "
-
 if [ ! -r "${file}" ]; then
   log_warning_msg "\n${file} is missing or cannot be accessed." 
   exit 1
 fi
 
 . $file
-
-if [ "$IFACE" = "" ]; then
-  log_failure_msg "\n${file} does not define an interface [IFACE]."
-  exit 1
-fi
 
 # Do not process this service if started by boot, and ONBOOT
 # is not set to yes
@@ -76,39 +69,67 @@ if [ "${IN_BOOT}" = "1" -a "${ONBOOT}" != "yes" ]; then
   exit 0
 fi
 
+log_info_msg "Bringing up the ${1} interface... "
+
+if [ -z "$PHYS" ]; then
+  log_failure_msg "\n${file} does not define any physical interfaces [PHYS]."
+  exit 1
+fi
+
 for S in ${SERVICE}; do
  if [ ! -n "${S}" -o ! -x "/lib/services/${S}" ]; then
-   MSG="\nUnable to process ${file}.  Either " 
-   MSG="${MSG}the SERVICE variable was not set "
-   MSG="${MSG}or the specified service cannot be executed."
+   MSG="\nUnable to process ${file}.  Either" 
+   MSG="${MSG} the SERVICE variable was not set"
+   MSG="${MSG} or the specified service cannot be executed."
    log_failure_msg "$MSG"
    exit 1
  fi
 done
 
-if [ -z "${CHECK_LINK}"         -o \
-       "${CHECK_LINK}" = "y"   -o \
-       "${CHECK_LINK}" = "yes" -o \
-       "${CHECK_LINK}" = "1" ]; then
+PHY_IDX=0
+for PHY in $PHYS ; do
+  if [ -z "${CHECK_LINK}"         -o \
+         "${CHECK_LINK}" = "y"   -o \
+         "${CHECK_LINK}" = "yes" -o \
+         "${CHECK_LINK}" = "1" ]; then
 
-  #  Bring up the interface
-  if ip link show ${IFACE} > /dev/null 2>&1; then
-     link_status=`ip link show ${IFACE}`
+    #  Bring up the interface
+    if ip link show ${PHY} > /dev/null 2>&1; then
+       link_status=`ip link show ${PHY}`
 
-     if [ -n "${link_status}" ]; then
-        if ! echo "${link_status}" | grep -q UP; then
-           ip link set ${IFACE} up
-        fi
-     fi
+       if [ -n "${link_status}" ]; then
+          if ! echo "${link_status}" | grep -q UP; then
+             ip link set ${PHY} up
+          fi
+       fi
 
-  else
-     log_warning_msg "\nInterface ${IFACE} doesn't exist."
-     exit 0
+    else
+       log_warning_msg "\nInterface ${PHY} doesn't exist."
+       exit 0
+    fi
+
+    # Link is up, so set MTU
+    if test -n "${MTU}"; then
+      # Use the proper MTU if there are multiple MTUs set in ${MTU}.
+      M=$(echo $MTU | awk -v idx=$PHY_IDX '{printf("%s", $idx);}')
+
+      # If there is only one ${MTU}, but multiple ${PHYS}, use ${MTU}.
+      test -z ${M} && M="${MTU}"
+
+      # Check if MTU has a "good" value.
+      if [ ${M} -gt 0 ] ; then
+        ip link set dev ${PHY} mtu ${M}
+      else
+        echo "Invalid MTU ${M}"
+      fi
+    fi
   fi
-fi
+
+  PHY_IDX=$((1 + ${PHY_IDX}))
+done
 
 for S in ${SERVICE}; do 
- IFCONFIG=${file} /lib/services/${S} ${IFACE} up
+  /lib/services/${S} ${file} up
 done
 
 # End /sbin/ifup
