Kernel config updates.
Also added the networking scripts pulled from BLFS with the ifup,
ifdown, and bridge changes I prototyped.

diff --git a/xlapp-bootscripts/ifdown b/xlapp-bootscripts/ifdown
--- a/xlapp-bootscripts/ifdown
+++ b/xlapp-bootscripts/ifdown
@@ -7,17 +7,12 @@
 # Authors     : Nathan Coulson - nathan@linuxfromscratch.org
 #               Kevin P. Fleming - kpfleming@linuxfromscratch.org
 # Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
-#               Qrux - qrux dot qed at gmail.com
 #
 # Version     : LFS 7.0
 #
 # Notes       : the IFCONFIG variable is passed to the scripts found
 #               in the /lib/services directory, to indicate what file the
 #               service should source to get interface specifications.
-#               Since bridging adds the possibility of two services,
-#               (e.g., one to create the bridge, the next to give it an
-#               IP), we allow calling multiple services--called in the
-#               order in which they were defined in the config file.
 #
 ########################################################################
 
@@ -27,30 +22,30 @@ USAGE="Usage: $0 [ -hV ] [--help] [--version] interface"
 VERSTR="LFS ifdown, version ${RELEASE}"
 
 while [ $# -gt 0 ]; do
-   case "$1" in
-      --help | -h)     help="y"; break ;;
+  case "$1" in
+     --help | -h)     help="y"; break ;;
 
-      --version | -V)  echo "${VERSTR}"; exit 0 ;;
+     --version | -V)  echo "${VERSTR}"; exit 0 ;;
 
-      -*)              echo "ifup: ${1}: invalid option" >&2
-                       echo "${USAGE}" >& 2
-                       exit 2 ;;
-                    
-      *)               break ;;
-   esac
+     -*)              echo "ifup: ${1}: invalid option" >&2
+                      echo "${USAGE}" >& 2
+                      exit 2 ;;
+
+     *)               break ;;
+  esac
 done
 
 if [ -n "$help" ]; then
-   echo "${VERSTR}"
-   echo "${USAGE}"
-   echo
-   cat << HERE_EOF
+  echo "${VERSTR}"
+  echo "${USAGE}"
+  echo
+  cat << HERE_EOF
 ifdown is used to bring down a network interface.  The interface
 parameter, e.g. eth0 or eth0:2, must match the trailing part of the
 interface specifications file, e.g. /etc/sysconfig/ifconfig.eth0:2.
 
 HERE_EOF
-   exit 0
+  exit 0
 fi
 
 file=/etc/sysconfig/ifconfig.${1}
@@ -61,51 +56,49 @@ file=/etc/sysconfig/ifconfig.${1}
 . /lib/lsb/init-functions 
 
 if [ ! -r "${file}" ]; then
-   log_warning_msg "${file} is missing or cannot be accessed."
-   exit 1
+  log_warning_msg "${file} is missing or cannot be accessed."
+  exit 1
 fi
 
 . ${file}
 
 if [ "$IFACE" = "" ]; then
-   log_failure_msg "${file} does not define an interface [IFACE]."
-   exit 1
+  log_failure_msg "${file} does not define an interface [IFACE]."
+  exit 1
 fi
 
-# Reverse input, so we things in the right order
-# (e.g., take down an IP address before blowing up the bridge).
-SERVICES=""
-for _S in $SERVICE ; do
-	SERVICES="${_S} $SERVICES"
-done
+# Reverse the order
+SERVICES=
+for S in ${SERVICE}; do SERVICES="${SERVICES} ${S}"; done
 
-# This will run the service script, if SERVICE is set
-for _S in $SERVICES ; do
-   if [ -n "${_S}" -a -x "/lib/services/${_S}" ]; then
-      if ip link show ${IFACE} > /dev/null 2>&1; then
-         IFCONFIG=${file} /lib/services/${_S} ${IFACE} down
-      else
-         log_warning_msg "Interface ${1} doesn't exist."
-      fi
-   else
+# This will run the service scripts
+if ip link show ${IFACE} > /dev/null 2>&1; then
+  for S in ${SERVICES}; do
+
+    if [ -n "${S}" -a -x "/lib/services/${S}" ]; then
+      IFCONFIG=${file} /lib/services/${S} ${IFACE} down
+    else
       MSG="Unable to process ${file}.  Either "
-      MSG="${MSG}the SERVICE variable was not set"
+      MSG="${MSG}the SERVICE variable was not set "
       MSG="${MSG}or the specified service cannot be executed."
       log_failure_msg "$MSG"
       exit 1
    fi
+ done
+else
+  log_warning_msg "Interface ${1} doesn't exist."
+fi
 
-   link_status=`ip link show ${IFACE} 2>/dev/null`
+link_status=`ip link show ${IFACE} 2>/dev/null`
 
-   if [ -n "${link_status}" ]; then
-      if [ "$(echo "${link_status}" | grep UP)" != "" ]; then
-         if [ "$(ip addr show ${IFACE} | grep 'inet ')" != ""  ]; then
-            log_info_msg "Bringing down the ${IFACE} interface..."
-            ip link set ${IFACE} down
-            evaluate_retval
-         fi
-      fi
-   fi
-done
+if [ -n "${link_status}" ]; then
+  if [ "$(echo "${link_status}" | grep UP)" != "" ]; then
+     if [ "$(ip addr show ${IFACE} | grep 'inet ')" != ""  ]; then
+        log_info_msg "Bringing down the ${IFACE} interface..."
+        ip link set ${IFACE} down
+        evaluate_retval
+     fi
+  fi
+fi
 
 # End /sbin/ifdown
diff --git a/xlapp-bootscripts/ifup b/xlapp-bootscripts/ifup
--- a/xlapp-bootscripts/ifup
+++ b/xlapp-bootscripts/ifup
@@ -7,17 +7,12 @@
 # Authors     : Nathan Coulson - nathan@linuxfromscratch.org
 #               Kevin P. Fleming - kpfleming@linuxfromscratch.org
 # Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
-#               Qrux - qrux dot qed at gmail.com
 #
 # Version     : LFS 7.0
 #
 # Notes       : The IFCONFIG variable is passed to the SERVICE script
 #               in the /lib/services directory, to indicate what file the
 #               service should source to get interface specifications.
-#               Since bridging adds the possibility of two services,
-#               (e.g., one to create the bridge, the next to give it an
-#               IP), we allow calling multiple services--called in the
-#               order in which they were defined in the config file.
 #
 ########################################################################
 
@@ -27,30 +22,30 @@ USAGE="Usage: $0 [ -hV ] [--help] [--version] interface"
 VERSTR="LFS ifup, version ${RELEASE}"
 
 while [ $# -gt 0 ]; do
-   case "$1" in
-      --help | -h)     help="y"; break ;;
+  case "$1" in
+     --help | -h)     help="y"; break ;;
 
-      --version | -V)  echo "${VERSTR}"; exit 0 ;;
-   
-      -*)              echo "ifup: ${1}: invalid option" >&2
-                       echo "${USAGE}" >& 2
-                       exit 2 ;;
-                       
-      *)               break ;;
-   esac
+     --version | -V)  echo "${VERSTR}"; exit 0 ;;
+
+     -*)              echo "ifup: ${1}: invalid option" >&2
+                      echo "${USAGE}" >& 2
+                      exit 2 ;;
+
+     *)               break ;;
+  esac
 done
 
 if [ -n "$help" ]; then
-   echo "${VERSTR}"
-   echo "${USAGE}"
-   echo
-   cat << HERE_EOF
+  echo "${VERSTR}"
+  echo "${USAGE}"
+  echo
+  cat << HERE_EOF
 ifup is used to bring up a network interface.  The interface
 parameter, e.g. eth0 or eth0:2, must match the trailing part of the
 interface specifications file, e.g. /etc/sysconfig/ifconfig.eth0:2.
 
 HERE_EOF
-   exit 0
+  exit 0
 fi
 
 file=/etc/sysconfig/ifconfig.${1}
@@ -63,58 +58,57 @@ file=/etc/sysconfig/ifconfig.${1}
 log_info_msg "Bringing up the ${1} interface... "
 
 if [ ! -r "${file}" ]; then
-   log_warning_msg "\n${file} is missing or cannot be accessed." 
-   exit 1
+  log_warning_msg "\n${file} is missing or cannot be accessed." 
+  exit 1
 fi
 
 . $file
 
 if [ "$IFACE" = "" ]; then
-   log_failure_msg "\n${file} does not define an interface [IFACE]."
-   exit 1
+  log_failure_msg "\n${file} does not define an interface [IFACE]."
+  exit 1
 fi
 
 # Do not process this service if started by boot, and ONBOOT
 # is not set to yes
 if [ "${IN_BOOT}" = "1" -a "${ONBOOT}" != "yes" ]; then
-   log_info_msg2 "skipped\n"
-   exit 0
+  log_info_msg2 "skipped\n"
+  exit 0
 fi
 
-# Sanitize input
-SERVICES=$(echo $SERVICE | sed "s/\s\+/ /")
+for S in ${SERVICES}; do
+ if [ ! -n "${S}" -o ! -x "/lib/services/${S}" ]; then
+   MSG="\nUnable to process ${file}.  Either " 
+   MSG="${MSG}the SERVICE variable was not set "
+   MSG="${MSG}or the specified service cannot be executed."
+   log_failure_msg "$MSG"
+   exit 1
+ fi
+done
 
-for _S in $SERVICES ; do
-   if [ -n "${_S}" -a -x "/lib/services/${_S}" ]; then
-      if [ -z "${CHECK_LINK}"         -o \
-              "${CHECK_LINK}" = "y"   -o \
-              "${CHECK_LINK}" = "yes" -o \
-              "${CHECK_LINK}" = "1" ]; then
+if [ -z "${CHECK_LINK}"         -o \
+       "${CHECK_LINK}" = "y"   -o \
+       "${CHECK_LINK}" = "yes" -o \
+       "${CHECK_LINK}" = "1" ]; then
 
-         #  Bring up the interface
-         if ip link show ${IFACE} > /dev/null 2>&1; then
-            link_status=`ip link show ${IFACE}`
+  #  Bring up the interface
+  if ip link show ${IFACE} > /dev/null 2>&1; then
+     link_status=`ip link show ${IFACE}`
 
-            if [ -n "${link_status}" ]; then
-               if ! echo "${link_status}" | grep -q UP; then
-                  ip link set ${IFACE} up
-               fi
-            fi
+     if [ -n "${link_status}" ]; then
+        if ! echo "${link_status}" | grep -q UP; then
+           ip link set ${IFACE} up
+        fi
+     fi
 
-         elif [ "BRIDGE" != ${_S} ] ; then
-            log_warning_msg "\nInterface ${IFACE} doesn't exist."
-         fi
-      fi
+  else
+     log_warning_msg "\nInterface ${IFACE} doesn't exist."
+     exit 0
+  fi
+fi
 
-      IFCONFIG=${file} /lib/services/${_S} ${IFACE} up
-
-   else
-      MSG="\nUnable to process ${file}.  Either " 
-      MSG="${MSG}the SERVICE variable was not set "
-      MSG="${MSG}or the specified service cannot be executed."
-      log_failure_msg "$MSG"
-      exit 1
-   fi
+for S in ${SERVICE}; do 
+ IFCONFIG=${file} /lib/services/${S} ${IFACE} up
 done
 
 # End /sbin/ifup
